---
- name: Nginx
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Install nginx
      pacman:
        name: nginx
        state: present

    - name: Enable & Start Nginx
      systemd:
        name: nginx
        enabled: yes

    - name: Download nginx conf
      get_url:
        url: https://gist.githubusercontent.com/nishantmodak/d08aae033775cb1a0f8a/raw/ebea0ae66e0a0188009accae2acba88cc646ddcd/nginx.conf.default
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      register: service_conf

    - name: Verify Nginx config
      become: yes
      command: nginx -t
      changed_when: true
      register: service_conf_validation
      when: service_conf.changed

    - name: restart nginx service
      service:
        name: nginx
        state: restarted
      when:
        service_conf_validation.changed

        #- name: Configure bashrc
        #  lineinfile:
        #    path: /home/salarmgh/.bashrc
        #    state: present
        #    line: |
        #      {{ bash_custom_config }}
